{
   "jobs": {
      "chart-test": {
         "runs-on": "self-hosted",
         "steps": [
            {
               "name": "Checkout repository",
               "uses": "actions/checkout@v2"
            }
         ]
      }
   },
   "name": "CI",
   "on": {
      "push": {
         "paths": [
            "**.js"
         ]
      }
   }
}
